### ISSUE TITLE
Enable UARTs 1, 4 and 5 on Beaglebone Black

### ISSUE THREAD

**Issue by jordicrosmompart** [cu-ecen-aeld/final-project-jordicrosmompart#12]
**Definition of Done (DoD)**

- Enable UART 1,4 and 5 on Beaglebone Black by patching its device tree.
- Verify that UARTs are enabled on the board.

**Comment by GuruprashanthKrishnakumar** [comment]
UART has been enabled on our own images.

**Note**
To get UART enabled on our image, we had to checkout buildroot version **2019.05.x** 
We have followed the [defconfig](https://github.com/MohitRane8/buildroot-assignments-base/blob/hw-beaglebone-black-uart/base_external/configs/aesd_beaglebone_defconfig) file provided here. This is because there have been significant changes to the beagleboard device tree. To enable UART for later buildroot versions, a device overlay might need to be used. 

Hence, for the purpose of moving the project forward, we are using the older version of buildroot (more specifically building linux using an older beagleboard source). We followed the steps provided [here](https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/Beagle-Bone-Black-Devicetree-Hardware-Support) after building our image and we are using the same [patch](https://github.com/MohitRane8/buildroot-assignments-base/blob/hw-beaglebone-black-uart/base_external/patches/linux/0001-Added-UART-1-4-and-5-support-for-BeagleBone-Black.patch) as provided here.

UART is now enabled on our image as well:
![image](https://user-images.githubusercontent.com/97482748/202867122-fd4871b4-ebb1-4890-b08b-d8acb4eba834.png)

Marking this issue as CLOSED. 

Commit associated - https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/commit/fac1be5ff53ffe07f6b2bb4365e17a69bc795a12
