### ISSUE TITLE
HM-11 BLE device driver implementation - User-space interfacing

### ISSUE THREAD

**Issue by GuruprashanthKrishnakumar** [cu-ecen-aeld/final-project-jordicrosmompart#5]
**Definition of Done (DOD)**
- Implement HM-11 BLE device configuration (service discovery, characteristic discovery, enabling indication/notification).
- User-space applications can interact with the driver through a set of ioctl commands.
- Error checking is performed by the LKM to guarantee that the commands performed against the HM-11 are correct.

**Blockers**
- [UART device driver implementation](https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/4) - COMPLETED

**Comment by jordicrosmompart** [comment]
The user-space interfacing has been completed for all essential commands required to configure the HM-11 module. This has been done by creating different ioctl commands, taking arguments as requested and providing responses both through parameters and return values.

The set of ioctl commands are defined in https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/blob/master/hm11_lkm/hm11_ioctl.h 

A user-space program has been created to test the correctness of the ioctl calls. The program can be found here: https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/tree/master/heart_rate_monitoring_server 
The datasheet which all the ioctl commands are based can be found here: http://www.jnhuamao.cn/index_en.asp?ID=1 (Click on BLE 4.0 modules to download datasheet in a ZIP)

The output of the kernel module responding to all ioctl commands: 
![image](https://user-images.githubusercontent.com/91290525/202947107-1fd6647c-2529-4248-b239-896d2817bf36.png)
The output of the user-space program is as follows (note that some error checks are not successful; this is on purpose for testing): 
![image](https://user-images.githubusercontent.com/91290525/202947638-b8d9f462-822f-4b22-a6fa-ab2879ece0fe.png)

The scripts to load/unload the LKM are also provided: https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/tree/master/hm11_lkm.

The last commit associated with this issue is the following: https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/commit/2593e961bf080d26fc1bbbedbc261317e6f7b60b

**Comment by jordicrosmompart** [comment]
Continuation of this issue: https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/13
